name: Ado to GitHub Migration

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: []
  pull_request:
    branches: []

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Checkout private tools
        uses: actions/checkout@v4
        with:
          repository: https://dev.azure.com/rinkeshputta0639/_git/avanza-cpg-batch-01
          token: ${{ secrets.GH_PAT }} # `GH_PAT` is a secret that contains your PAT







      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

