name: Ado to GitHub Migration

# Controls when the workflow will run
on:
  workflow_dispatch:
  push:
      branches: ['main']
  pull_request:
      branches: []

# variables:
#  - name: 'azure_devops_org'
#    default: 'rinkeshputta0639'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # - name: Checkout private tools
      #   uses: actions/checkout@v4
      #   with:
      #     repository: https://dev.azure.com/rinkeshputta0639/avanza-cpg-batch-01
      #     token: ${{ secrets.GH_PAT }} # `GH_PAT` is a secret that contains your PAT


      - name: Set up Git for Azure DevOps
        run: |
          git config --global url."https://{YOUR_AZURE_DEVOPS_ORG}.visualstudio.com".insteadOf "https://dev.azure.com"
          git config --global credential.helper store

      - name: Checkout Azure DevOps repository
        env:
          AZURE_DEVOPS_TOKEN: ${{ secrets.AZURE_DEVOPS_TOKEN }}
        run: |
          git clone https://$AZURE_DEVOPS_TOKEN@dev.azure.com/$YOUR_AZURE_DEVOPS_ORG/$YOUR_PROJECT/_git/$REPO_NAME
          
      - name: List files in repo (Optional)
        run: ls -la {REPO_NAME}





      # # Runs a single command using the runners shell
      # - name: Run a one-line script
      #   run: echo Hello, world!

