name: Ado to GitHub Migration

# Controls when the workflow will run
on:
  workflow_dispatch:
  push:
      branches: ['main']
  pull_request:
      branches: []

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Git for Azure DevOps
        env:
          YOUR_AZURE_DEVOPS_ORG: ${{ vars.YOUR_AZURE_DEVOPS_ORG }}
        run: |
          git config --global url."https://{YOUR_AZURE_DEVOPS_ORG}.visualstudio.com".insteadOf "https://dev.azure.com"
          git config --global credential.helper store

      - name: Checkout Azure DevOps repository
        env:
          AZURE_DEVOPS_TOKEN: ${{ secrets.AZURE_DEVOPS_TOKEN }}
          YOUR_AZURE_DEVOPS_ORG: ${{ vars.YOUR_AZURE_DEVOPS_ORG }}
          YOUR_PROJECT: ${{ vars.YOUR_PROJECT }}
          REPO_NAME: ${{ vars.REPO_NAME }}
        run: |
          git clone https://$AZURE_DEVOPS_TOKEN@dev.azure.com/$YOUR_AZURE_DEVOPS_ORG/$YOUR_PROJECT/_git/$REPO_NAME
          ls -la
          
      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: latest

      - name: Terraform Init
        run: |
          terraform init


